### ISSUE TITLE
Valid flag + No message will crash program

### ISSUE THREAD

**Issue by ajtran303** [ajtran303/horizontal_ruler#14]
Full Traceback:

```
🔮 vetur ~ cli  $banner -b
Traceback (most recent call last):
	5: from /Users/vetur/random_code/banner/banner.rb:68:in `<main>'
	4: from /Users/vetur/random_code/banner/banner.rb:68:in `new'
	3: from /Users/vetur/random_code/banner/banner.rb:21:in `initialize'
	2: from /Users/vetur/random_code/banner/banner.rb:21:in `new'
	1: from /Users/vetur/random_code/banner/lib/letter_spacer.rb:6:in `initialize'
/Users/vetur/random_code/banner/lib/letter_spacer.rb:24:in `generate_spaced_message': undefined method `join' for nil:NilClass (NoMethodError)

```

**Comment by ajtran303** [comment]
Compare to this Traceback:

```
🔮 vetur ~ cli  $banner 'hello'
Rule not found. Find rules: $ ruby banner.rb -hr
```

**Comment by ajtran303** [comment]
If there is an invalid first argument, there will be a "Rule not found" message.

However, if there is a valid first argument but no second argument, the code execution will continue until `nil` is passed into LetterSpacer.new.

Then we get the traceback in the original post.

**Comment by ajtran303** [comment]
A possible solution would be to make a validation check inside of the LetterSpacer class so that it will only take the required data type.

**Comment by ajtran303** [comment]
Hey!! 'banner' is already a command. It was made in May 6, 1986. To make banners.

https://www.freebsd.org/cgi/man.cgi?query=banner&manpath=2.10+BSD

I mean, I'm not using it so I'd be okay with using 'banner' as an Alias but this is interesting information.
